import { Product } from "@/types/product";

const shopData: Product[] = [
  {
    title: "1 Mukhi Rudraksha",
    reviews: 15,
    slug: "1-mukhi-rudraksha",
    price: 59.0,
    discountedPrice: 29.0,
    img: "/images/products/1-14-mukhi/1.png",
    images: ["/images/products/1-14-mukhi/1.png"],
    id: 1,
    imgs: {
      thumbnails: ["/images/products/1-14-mukhi/1.png", "/images/products/1-14-mukhi/1.png"],
      previews: ["/images/products/1-14-mukhi/1.png", "/images/products/1-14-mukhi/1.png"],
    },
  },
  {
    title: "2 Mukhi Rudraksha",
    reviews: 5,
    price: 899.0,
    slug: "2-mukhi-rudraksha",
    discountedPrice: 99.0,
    img: "/images/products/1-14-mukhi/2.png",
    images: ["/images/products/1-14-mukhi/2.png"],
    id: 2,
    imgs: {
      thumbnails: ["/images/products/1-14-mukhi/2.png", "/images/products/1-14-mukhi/2.png"],
      previews: ["/images/products/1-14-mukhi/2.png", "/images/products/1-14-mukhi/2.png"],
    },
  },
  {
    title: "3 Mukhi Rudraksha",
    reviews: 5,
    price: 59.0,
    discountedPrice: 29.0,
    slug: "3-mukhi-rudraksha",
    img: "/images/products/1-14-mukhi/3.png",
    images: ["/images/products/1-14-mukhi/3.png"],
    id: 3,
    imgs: {
      thumbnails: ["/images/products/1-14-mukhi/3.png", "/images/products/1-14-mukhi/3.png"],
      previews: ["/images/products/1-14-mukhi/3.png", "/images/products/1-14-mukhi/3.png"],
    },
  },
  {
    title: "4 Mukhi Rudraksha",
    reviews: 5,
    price: 59.0,
    discountedPrice: 29.0,
    slug: "4-mukhi-rudraksha",
    img: "/images/products/1-14-mukhi/4.png",
    images: ["/images/products/1-14-mukhi/4.png"],
    id: 4,
    imgs: {
      thumbnails: ["/images/products/1-14-mukhi/4.png", "/images/products/1-14-mukhi/4.png"],
      previews: ["/images/products/1-14-mukhi/4.png", "/images/products/1-14-mukhi/4.png"],
    },
  },
  {
    title: "5 Mukhi Rudraksha",
    reviews: 5,
    price: 59.0,
    discountedPrice: 29.0,
    slug: "5-mukhi-rudraksha",
    img: "/images/products/1-14-mukhi/5.png",
    images: ["/images/products/1-14-mukhi/5.png"],
    id: 5,
    imgs: {
      thumbnails: ["/images/products/1-14-mukhi/5.png", "/images/products/1-14-mukhi/5.png"],
      previews: ["/images/products/1-14-mukhi/5.png", "/images/products/1-14-mukhi/5.png"],
    },
  },
  {
    title: "6 Mukhi Rudraksha",
    reviews: 5,
    price: 59.0,
    discountedPrice: 29.0,
    slug: "6-mukhi-rudraksha",
    img: "/images/products/1-14-mukhi/6.png",
    images: ["/images/products/1-14-mukhi/6.png"],
    id: 6,
    imgs: {
      thumbnails: ["/images/products/1-14-mukhi/6.png", "/images/products/1-14-mukhi/6.png"],
      previews: ["/images/products/1-14-mukhi/6.png", "/images/products/1-14-mukhi/6.png"],
    },
  },
  {
    title: "7 Mukhi Rudraksha",
    reviews: 5,
    price: 59.0,
    discountedPrice: 29.0,
    slug: "7-mukhi-rudraksha",
    img: "/images/products/1-14-mukhi/7.png",
    images: ["/images/products/1-14-mukhi/7.png"],
    id: 7,
    imgs: {
      thumbnails: ["/images/products/1-14-mukhi/7.png", "/images/products/1-14-mukhi/7.png"],
      previews: ["/images/products/1-14-mukhi/7.png", "/images/products/1-14-mukhi/7.png"],
    },
  },
  {
    title: "8 Mukhi Rudraksha",
    reviews: 5,
    price: 59.0,
    discountedPrice: 29.0,
    slug: "8-mukhi-rudraksha",
    img: "/images/products/1-14-mukhi/8.png",
    images: ["/images/products/1-14-mukhi/8.png"],
    id: 8,
    imgs: {
      thumbnails: ["/images/products/1-14-mukhi/8.png", "/images/products/1-14-mukhi/8.png"],
      previews: ["/images/products/1-14-mukhi/8.png", "/images/products/1-14-mukhi/8.png"],
    },
  },
  {
    title: "9 Mukhi Rudraksha",
    reviews: 5,
    price: 59.0,
    discountedPrice: 29.0,
    slug: "9-mukhi-rudraksha",
    img: "/images/products/1-14-mukhi/9.png",
    images: ["/images/products/1-14-mukhi/9.png"],
    id: 9,
    imgs: {
      thumbnails: ["/images/products/1-14-mukhi/9.png", "/images/products/1-14-mukhi/9.png"],
      previews: ["/images/products/1-14-mukhi/9.png", "/images/products/1-14-mukhi/9.png"],
    },
  },
  {
    title: "10 Mukhi Rudraksha",
    reviews: 5,
    price: 59.0,
    discountedPrice: 29.0,
    slug: "10-mukhi-rudraksha",
    img: "/images/products/1-14-mukhi/10.png",
    images: ["/images/products/1-14-mukhi/10.png"],
    id: 10,
    imgs: {
      thumbnails: ["/images/products/1-14-mukhi/10.png", "/images/products/1-14-mukhi/10.png"],
      previews: ["/images/products/1-14-mukhi/10.png", "/images/products/1-14-mukhi/10.png"],
    },
  },
  {
    title: "11 Mukhi Rudraksha",
    reviews: 5,
    price: 59.0,
    discountedPrice: 29.0,
    slug: "11-mukhi-rudraksha",
    img: "/images/products/1-14-mukhi/11.png",
    images: ["/images/products/1-14-mukhi/11.png"],
    id: 11,
    imgs: {
      thumbnails: ["/images/products/1-14-mukhi/11.png", "/images/products/1-14-mukhi/11.png"],
      previews: ["/images/products/1-14-mukhi/11.png", "/images/products/1-14-mukhi/11.png"],
    },
  },
  {
    title: "12 Mukhi Rudraksha",
    reviews: 5,
    price: 59.0,
    discountedPrice: 29.0,
    slug: "12-mukhi-rudraksa",
    img: "/images/products/1-14-mukhi/12.png",
    images: ["/images/products/1-14-mukhi/12.png"],
    id: 12,
    imgs: {
      thumbnails: ["/images/products/1-14-mukhi/12.png", "/images/products/1-14-mukhi/12.png"],
      previews: ["/images/products/1-14-mukhi/12.png", "/images/products/1-14-mukhi/12.png"],
    },
  },
  {
    title: "13 Mukhi Rudraksha",
    reviews: 5,
    price: 59.0,
    discountedPrice: 29.0,
    slug: "13-mukhi-rudraksha",
    img: "/images/products/1-14-mukhi/13.png",
    images: ["/images/products/1-14-mukhi/13.png"],
    id: 13,
    imgs: {
      thumbnails: ["/images/products/1-14-mukhi/13.png", "/images/products/1-14-mukhi/13.png"],
      previews: ["/images/products/1-14-mukhi/13.png", "/images/products/1-14-mukhi/13.png"],
    },
  },
  {
    title: "14 Mukhi Rudraksha",
    reviews: 5,
    price: 59.0,
    discountedPrice: 29.0,
    slug: "14-mukhi-rudraksha",
    img: "/images/products/1-14-mukhi/14.png",
    images: ["/images/products/1-14-mukhi/14.png"],
    id: 14,
    imgs: {
      thumbnails: ["/images/products/1-14-mukhi/14.png", "/images/products/1-14-mukhi/14.png"],
      previews: ["/images/products/1-14-mukhi/14.png", "/images/products/1-14-mukhi/14.png"],
    },
  },
];

export default shopData;